[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
staking_program = "BURhYk8eb8392c4rNAWTXpg2pK3H5KynWXn4ybDVsky7"

[programs.localnet]
staking_program = "BURhYk8eb8392c4rNAWTXpg2pK3H5KynWXn4ybDVsky7"

[programs.mainnet]
staking_program = "BURhYk8eb8392c4rNAWTXpg2pK3H5KynWXn4ybDVsky7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/mainnet-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
