[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
staking_program = "2uyyshjWoWab7ECpbwv8dSTQJpbPNBubyD4eGK1JsSGQ"

[programs.localnet]
staking_program = "2uyyshjWoWab7ECpbwv8dSTQJpbPNBubyD4eGK1JsSGQ"

[programs.mainnet]
staking_program = "2uyyshjWoWab7ECpbwv8dSTQJpbPNBubyD4eGK1JsSGQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/mainnet-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
